### ISSUE TITLE
在"SkGachas.cs"中是否应将"right"的值改为"Count-1"

### ISSUE THREAD

**Issue by d2033801** [MomoiAiri/MinoriBot#1]
如图，当我手动调整json文件中元素数量为【1】时
![图片](https://github.com/MomoiAiri/MinoriBot/assets/70478207/8b252af0-224f-4396-92ca-44282aa5290d)
此时`SkDataBase.skGachaCeilItemscs.Count`的值为1
![图片](https://github.com/MomoiAiri/MinoriBot/assets/70478207/03162ce1-00b1-44b4-98ac-61a0617fa8f7)

而在
```C#
//SkGachas.cs，132行
        public string GetGachaPickUpType()
        {
            int left = 0;
            int right = SkDataBase.skGachaCeilItemscs.Count;
            int mid;
            while (left <= right)
            {
                mid = (left + right) / 2;
                if (SkDataBase.skGachaCeilItemscs[mid].gachaId < id)
                {
                    left = mid + 1;
                }
                else if (SkDataBase.skGachaCeilItemscs[mid].gachaId > id)
                {
                    right = mid - 1;
                }
                ...
        }
```
中，right获取到的值为1，在循环第一轮后变量分别为`mid == 0; left == 1; right==1`，此时仍满足条件
第二轮开始时会使`mid = 1;`但事实上列表中只有`SkDataBase.skGachaCeilItemscs[0]`元素，此时访问`SkDataBase.skGachaCeilItemscs[1]`会导致越界

**Comment by d2033801** [comment]
以及fes卡（包括一周年池）似乎在sekaiviewer的`gachaCeilItems.json`数据里并没有被提及/算作限定卡，不知是否应有别的方案替代

**Comment by MomoiAiri** [comment]
skGachaCeilItems.Count的问题确实是我疏忽了，关于fes卡的问题我也在sekai-master-db-diff中没有找到其他能确定是否为常驻或限定的方法，鉴于目前烤目前所有fes池的up卡都是限定，直接根据卡池标题判断了
